### ISSUE TITLE
Change Voice Command

### ISSUE THREAD

**Issue by funky81** [valerino/VGCamera#1]
Hi, Thanks for your beautiful code. Anyway, could you give me idea how to change the voice command? I looking everywhere but still cant change into different voice command than your code.

Please help. Thanks

**Comment by valerino** [comment]
sorry, just found your issue. the project is discontinued since my google glass has broke long ago and i couldn't find an affordable replacement. so, sorry but i can't help (and also i forgot almost everything of this project now) :)
cheers!
